### ISSUE TITLE
start xmonad error.

### ISSUE THREAD

**Issue by leaeasy** [lynnard/VIMonad#1]
I found some error in .xmonad/xmonad.hs file: getMyScriptDir,getMyXMonadDir.
When I change getMyScript to getScriptDir, and getMyXmonadDir to getXmonaDir.
The log tells me something wrong:

  1 
  2 xmonad.hs:169:26:
  3     Couldn't match type ‘Rational -> Rational -> ManageHook’
  4                   with ‘Query (Data.Monoid.Endo WindowSet)’
  5     Expected type: ManageHook
  6       Actual type: Rational -> Rational -> ManageHook
  7     Probable cause: ‘rightPanelHook’ is applied to too few arguments
  8     In the ‘launchHook’ field of a record
  9     In the expression:
 10       tgd
 11         {taskGroupName = "pidgin-buddy",
 12          filterPredicate = isPidginBuddyList, launchHook = rightPanelHook,
 13          construct = \ n _ -> mkNamedScratchpad scratchpads "pidgin",
 14          windowStyle = windowStyleFromList
 15                          [rightPanelHook, leftPanelHook, doSink]}
 16 
 17 xmonad.hs:171:48:
 18     Couldn't match type ‘Rational -> Rational -> ManageHook’
 19                   with ‘Query (Data.Monoid.Endo WindowSet)’
 20     Expected type: ManageHook
 21       Actual type: Rational -> Rational -> ManageHook
 22     Probable cause: ‘rightPanelHook’ is applied to too few arguments
 23     In the expression: rightPanelHook
 24     In the first argument of ‘windowStyleFromList’, namely
 25       ‘[rightPanelHook, leftPanelHook, doSink]’

**Comment by lingnand** [comment]
The auxiliary files have just been updated to work with the newest VIMonad.

To pull in the changes I'd suggest you to redo the steps 2 and 3 under the **Steps** in `README`.

Note the README has been updated to shine some light on the new features as well, notably, [Dynamic Prompt](https://github.com/lynnard/vimonad#dynamic-prompt). One of these features is inputting Chinese in the prompt, which might be useful to you.

**Comment by lingnand** [comment]
Can you confirm if it works?
